blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.PostView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.PostDetail.as_view(), name='detail'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^post_add/$', views.PostCreate.as_view(), name='post_add'),
    url(r'^(?P<pk>\d+)/post_edit/$', views.PostUpdate.as_view(), name='post_edit'),
    url(r'^(?P<pk>\d+)/post_delete/$', views.PostDelete.as_view(), name='post_delete'),
    url(r'^post_drafts/$', views.PostDraftList.as_view(), name='post_drafts'),
    url(r'^(?P<pk>\d+)/post_publish/$', views.post_publish, name='post_publish'),
    url(r'^(?P<pk>\d+)/add_comment/$', views.add_comment_to_post, name='add_comment'),
    url(r'^(?P<pk>\d+)/approve_comment/$', views.approve_comment, name='approve_comment'),
    url(r'^(?P<pk>\d+)/remove_comment/$', views.remove_comment, name='remove_comment'),
]

blog_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'})
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=250)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk':self.pk})

    def approve_comments(self):
        return self.comments.filter(approved_comment = True)


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:index')

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('author', 'title', 'text')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textareainput'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textareainput'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm, CommentForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required


class PostView(ListView):
    model = Post
    context_object_name = 'all_posts'

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetail(DetailView):
    model = Post


class AboutView(TemplateView):
    template_name = 'blog/about.html'

class PostCreate(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login/'
    redirect_field_name = 'blog/details.html'
    model = Post
    form_class = PostForm

class PostUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/accounts/login/'
    redirect_field_name = 'blog/details.html'
    model = Post
    form_class = PostForm

class PostDelete(LoginRequiredMixin, DeleteView):
    login_url = '/accounts/login/'
    redirect_field_name = 'blog/details.html'
    model = Post
    success_url = reverse_lazy('blog:index')

class PostDraftList(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    redirect_field_name = 'blog/detail.html'
    model = Post
    context_object_name = 'post_drafts'
    template_name = 'blog/post_draft_list.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:detail', pk=pk)

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:detail', pk=post.pk)

    else:
        form=CommentForm()
        return render(request, 'blog/comment_form.html', {'form':form})

@login_required
def approve_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:detail', pk=comment.post.pk)

@login_required
def remove_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:detail', pk=post_pk)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block body %}


<h1>About us</h1>
<p>This is a site that gives you details about bollywood stars and lets you add comments</p>


{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Fun Blog{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/styles.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>

    <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'blog:index' %}">Fun Blog</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'blog:index' %}">Home</a></li>
      <li><a href="{% url 'blog:about' %}">About</a></li>
      <li><a href="#">GitHub</a></li>
      <li><a href="#">LinkedIn</a></li>
    </ul>
      <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'blog:post_drafts' %}">Drafts</a></li>
      <li><a href="{% url 'blog:post_add' %}">Add Posts</a></li>
          {% if user.is_authenticated %}
      <li><a>Welcome {{user|title}}</a></li>
      <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
      <li><a href="{% url 'login' %}">Login</a></li>
      <li><a href="#">Register</a></li>
          {% endif %}
    </ul>
  </div>
</nav>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block body %}

<h2>Add a new comment</h2>
    {{field.errors}}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" class="btn btn-primary" />

</form>



{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block body %}

<h2>Are you sure you want to delete this post</h2>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger" />
    <a href="{% url 'blog:detail' post.id %}" class="btn btn-warning">Cancel</a>

</form>



{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block body %}

<h1>{{post.title}}</h1>
{% if post.published_date %}
    <p>{{post.published_date}}</p>
{% else %}
    <a class="btn btn-primary" href="{% url 'blog:post_publish' post.id %}">Publish</a>
{%endif%}

<p>{{post.text|safe|linebreaksbr}}</p>
{% if user.is_authenticated%}
<a href="{% url 'blog:post_edit' post.id %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
<a href="{% url 'blog:post_delete' post.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
{% endif %}

<hr>

<a class="btn btn-primary comment_button" href="{% url 'blog:add_comment' post.id %}">Add Comment</a>

{% for comment in post.comments.all %}
<div>
{% if user.is_authenticated or post.approve_comments %}
<p>
    <strong>{{comment.author}}</strong>
    ({{comment.created_date|timesince}} ago)
    {% if not comment.approved_comment %}
    <a href="{% url 'blog:approve_comment' comment.id %}" class="btn btn-default"><span class="glyphicon glyphicon-ok"></span></a>
    <a href="{% url 'blog:remove_comment' comment.id %}" class="btn btn-default"><span class="glyphicon glyphicon-trash"></span></a>
    {% endif %}
</p>

    <p>{{comment|safe|linebreaksbr}}</p><br/>
{% endif %}
</div>
{% empty %}
    <p>Be the first to add a comment..</p>

{% endfor %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block body %}

{% for post in post_drafts %}
<h1><a href="{% url  'blog:detail' post.id %}">{{post.title}}</a></h1>
{{post.created_date|date:"M d Y"}}

{% endfor %}


{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block body %}

<h2>Add a new post</h2>
    {{field.errors}}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" class="btn btn-primary" />

</form>



{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block body %}


{% for post in all_posts %}
<h1><a href="{% url 'blog:detail' post.id %}">{{post.title}}</a></h1>
<p>{{post.published_date}}</p>
<p><a href="{% url 'blog:detail' post.id %}">Comments:({{post.approve_comments.count}})</a></p><br>
{% endfor %}


{% endblock %}